Fix/ingress template fixing
kouprlabs/voltaserve-helm pull request #12
Opened 2024-07-12 17:32 UTC by Mrkazik99

2024-07-12 17:57 UTC, loboda4450 approved these changes

2024-07-12 18:13 UTC, dsonck92 commented
Wait, how is this even necessary? Shouldn't minio just only receive the values directly under the `minio` settings?

2024-07-12 18:21 UTC, dsonck92 requested changes
I do realize that this might be out of scope since it was already present. But I'm not sure when they slipped in or if they have to be removed from the initial version

2024-07-12 18:21 UTC, dsonck92 commented on values.yaml
> +                }'
I'm not a fan. These would not work in my cluster. I recommend setting them to just {}

2024-07-12 18:26 UTC, dsonck92 commented on values.yaml
> +            webdavSecretName: null
This is an unconventional tls section. Usually I see charts directly dumping the `tls` slice through `toYaml`, since it gives the user no limitations on TLS configuration, while still being minimal

2024-07-12 18:26 UTC, dsonck92 commented on values.yaml
> +            webdavSecretName: null
I would actually take the `minio` chart as example.

2024-07-12 18:47 UTC, dsonck92 commented
> Wait, how is this even necessary? Shouldn't minio just only receive the values directly under the `minio` settings?

I will have a look what the linter is complaining about and see if it's fixable without introducing a whole `voltaserve` layer in our `values.yaml`

2024-07-12 18:48 UTC, Mrkazik99 commented on values.yaml
> +                }'
So the values were here with initial commit I forgot to remove them, I planned to perform a cleanup along with creating two values files

2024-07-12 18:50 UTC, dsonck92 commented on values.yaml
> +                }'
Alright, cool, I will consider this resolved for now then, considering the shape is correct

2024-07-12 18:56 UTC, dsonck92 requested changes

2024-07-12 18:56 UTC, dsonck92 commented on values.yaml
> +                {}
```suggestion
                []
        webdav:
            enabled: true
            annotations:
                {}
            host: webdav.public.url
            className: nginx-public
            tls:
                []
```
I'm curious why the linter doesn't care

2024-07-12 18:57 UTC, loboda4450 commented on values.yaml
> +                {}
idk if both of those values do not represent null

2024-07-12 18:59 UTC, dsonck92 commented on values.yaml
> +                {}
Well, I'm wondering if it can be overridden as array if it's defined as object here. We might want to lint with common customization overrides

2024-07-12 19:06 UTC, dsonck92 commented
I can't reproduce the linting issue if I remove the voltaserve prefix, so I want to test this on the CI

2024-07-12 19:07 UTC, loboda4450 commented
> I can't reproduce the linting issue if I remove the voltaserve prefix, so I want to test this on the CI

Let's go for that, the issue is not present on my side too.

2024-07-12 19:17 UTC, dsonck92 commented on templates/ingress.yaml
>  ---
I think, now that these are tightly coupled to ui and webdav, we probably want to place these separate in a ui/ingress.yaml and webdav/ingress.yaml

2024-07-12 19:18 UTC, dsonck92 commented
I think other than those 2 small nits, I can agree with the result. We can always iterate on it later during a cleanup sweep

2024-07-12 23:31 UTC, dsonck92 commented
LGTM

2024-07-12 23:31 UTC, dsonck92 approved these changes

2024-07-12 23:34 UTC, dsonck92 approved these changes

2024-07-13 03:28 UTC, loboda4450 approved these changes

2024-07-13 12:41 UTC, loboda4450 approved these changes

2024-07-13 20:49 UTC, dsonck92 approved these changes

2024-07-13 20:55 UTC, dsonck92 approved these changes

2024-07-13 20:55 UTC, merged