chore: issue templates
kouprlabs/voltaserve-helm pull request #13
Opened 2024-07-12 19:01 UTC by loboda4450

Created standarized issue templates with automatic label assignment. Will be useful just to have a shared templates for clarity.

2024-07-12 19:23 UTC, dsonck92 requested changes

2024-07-12 19:23 UTC, dsonck92 commented on .github/ISSUE_TEMPLATES/ama.md
> +**Thank you for reaching out!**
I think this should be marked as a comment? To prevent every issue with this (and other templates) to accidentally include this text at the bottom

2024-07-12 19:23 UTC, dsonck92 commented on .github/ISSUE_TEMPLATES/ama.md
> +## Ask me anything
Is this text going to be included inside the issue body?

2024-07-12 19:24 UTC, dsonck92 commented
I have to admit that I don't have experience with these templates, but they sound useful, I would just be careful not to include things that people end up forgetting to remove

2024-07-12 19:28 UTC, loboda4450 commented on .github/ISSUE_TEMPLATES/ama.md
> +## Ask me anything
Yup

2024-07-12 20:04 UTC, dsonck92 commented on .github/ISSUE_TEMPLATES/ama.md
> +## Ask me anything
Because in that case I'm curious what the purpose is for the header here. As it will render out as

# Issue title

## Ask me anything

...  rest

2024-07-12 20:24 UTC, loboda4450 commented on .github/ISSUE_TEMPLATES/ama.md
> +## Ask me anything
Where that issue title comes from? It is in a separate place.

2024-07-13 11:53 UTC, dsonck92 commented on .github/ISSUE_TEMPLATES/ama.md
> +## Ask me anything
Yes, I'm wondering about the purpose of including the "Ask me anything header". I don't think it is necessary as the issue title already carries the idea. A random "Ask me anything" inside the body is probably more noise.

2024-07-14 16:20 UTC, Mrkazik99 approved these changes

2024-07-17 17:29 UTC, dsonck92 approved these changes

2024-07-17 17:30 UTC, merged